# Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
enable-beta-ecosystems: true # for opentofu-support
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "gardenlinux/garden-linux-maintainers"

  - package-ecosystem: "pip"
    directory: "/tests/util"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase-if-necessary"
    reviewers:
      - "gardenlinux/garden-linux-maintainers"
