name: test_flavor
on:
  workflow_call:
jobs:
  test:
    name: Build and cache test distribution
    runs-on: "ubuntu-24.04"
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # pin@v5.0.1
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends make curl jq unzip qemu-utils
      - name: Build test distribution
        run: |
          cd tests-ng
          make -f util/build.makefile
          touch .build/.gh_artifact
      - name: Upload test distribution artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # pin@v5.0.0
        with:
          name: test-distribution
          path: tests-ng/.build
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 7
