name: build garden linux container
on:
  workflow_call:
env:
  IMAGE_NAME: gardenlinux/integration-test
jobs:
  integration_test_container:
    name: make integration test container
    runs-on: ec2-gardenlinux-amd64
    steps:
      - uses: actions/checkout@v3

      - name: login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | sudo podman login ghcr.io -u $ --password-stdin

      - name: make integration test container
        run: make --directory=container build-integration-test

      - name: upload integration test container to ghcr.io
        run: |
          sudo podman tag "$IMAGE_NAME:$(bin/garden-version)" "ghcr.io/gardenlinux/$IMAGE_NAME:$(bin/garden-version)"
          sudo podman tag "$IMAGE_NAME:$(bin/garden-version)" "ghcr.io/gardenlinux/$IMAGE_NAME:$GITHUB_SHA"
          sudo podman push "ghcr.io/gardenlinux/$IMAGE_NAME:$(bin/garden-version)"
          sudo podman push "ghcr.io/gardenlinux/$IMAGE_NAME:$GITHUB_SHA"
