name: Call check build reproducibility



# To be able to test actions on a different branch than main
on:
  push:
    branches:
      - "feat/check-reproducibility"

jobs:
  call:
    uses: ./.github/workflows/reproducable_test.yml
    permissions:
      actions: write
      id-token: write
      packages: write
    with:
      nightly: "Two new builds"
