name: test_flavor
on:
  workflow_call:
    inputs:
      arch:
        type: string
        default: "amd64"
      flavor:
        type: string
        required: true
jobs:
  test:
    name: Test-NG flavor in QEMU ${{ inputs.flavor }} (${{ inputs.arch }})
    # runs-on: ${{ inputs.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    runs-on: "ubuntu-24.04"
    if: ${{ inputs.flavor != 'skip' }}
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    env:
      CNAME: ""
    permissions:
      actions: write
    steps:
      - name: install qemu
        run: |
          sudo apt-get update
          sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends qemu-utils qemu-system-x86 qemu-system-arm swtpm socat libxml2-utils
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5.0.0
        with:
          submodules: true
      - uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # pin@v4.3.0
        with:
          path: |
            COMMIT
            VERSION
          key: build-${{ inputs.flavor }}-${{ inputs.arch }}-${{ github.run_id }}
          fail-on-cache-miss: true
      - name: Download test distribution artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # pin@v5.0.0
        with:
          name: test-distribution
          path: tests-ng/.build
      - name: Load certs artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # pin@v5.0.0
        with:
          name: certs
          path: cert/
      - name: Determine CNAME
        id: cname
        uses: gardenlinux/python-gardenlinux-lib/.github/actions/features_parse@2c47ca58891eefa3587954fadf59153317ad9e0c # pin@0.10.2
        with:
          flags: --cname ${{ inputs.flavor }}-${{ inputs.arch }} cname
      - name: Set CNAME
        run: |
          echo "CNAME=${{ steps.cname.outputs.result }}" | tee -a "$GITHUB_ENV"
      - name: Load flavor build artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # pin@v5.0.0
        with:
          name: build-${{ inputs.flavor }}-${{ inputs.arch }}
      - name: unpack build artifacts
        run: |
          mkdir ".build"
          tar -C .build -xzf $CNAME.tar.gz
          rm "$CNAME.tar.gz"
          tree .build
        # TODO: handle skipping better
      - name: New Test Framework
        run: |
          if [ ! -e ".build/$CNAME.raw" ]; then
            if [ -e ".build/$CNAME.ova" ]; then
              echo "extracting ova"
              tar xvf ".build/$CNAME.ova" -C .build
              ls -la .build
            fi
            if [ -e ".build/$CNAME.vhd" ]; then
              echo "converting vhd to raw"
              qemu-img convert -f vpc -O raw ".build/$CNAME.vhd" ".build/$CNAME.raw"
            elif [ -e ".build/$CNAME.qcow2" ]; then
              echo "converting qcow2 to raw"
              qemu-img convert -f qcow2 -O raw ".build/$CNAME.qcow2" ".build/$CNAME.raw"
            elif [ -e ".build/$CNAME.vmdk" ]; then
              echo "converting vmdk to raw"
              qemu-img convert -f vmdk -O raw ".build/$CNAME.vmdk" ".build/$CNAME.raw"
            elif [ -e ".build/$CNAME.gcpimage.tar.gz" ]; then
              echo "converting gcpimage to raw"
              tar -C .build -xzf ".build/$CNAME.gcpimage.tar.gz"
              mv ".build/disk.raw" ".build/$CNAME.raw"
            fi
          fi
          if [ -e ".build/$CNAME.raw" ]; then
            ./test-ng ".build/$CNAME.raw"
          elif [ -e ".build/$CNAME.pxe.tar.gz" ]; then
            ./test-ng ".build/$CNAME.pxe.tar.gz"
          elif [ -e ".build/$CNAME.oci" ]; then
            echo "skipping oci test"
            exit 0
          else
            echo "no raw or pxe file, QEMU test failed"
            exit 1
          fi
      - name: Copy test results to build directory
        if: always()
        run: |
          cp tests-ng/log/qemu.test-ng.log .build/${CNAME}.qemu.test-ng.log || true
          cp tests-ng/log/qemu.test-ng.xml .build/${CNAME}.qemu.test-ng.xml || true
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # pin@v4.6.2
        if: always()
        with:
          if-no-files-found: ignore
          name: qemu-test-ng-${{ env.CNAME }}
          path: |
            .build/${{ env.CNAME }}.qemu.test-ng.log
            .build/${{ env.CNAME }}.qemu.test-ng.xml
